### PR TITLE
[WIP] php 7 compatibility replace String Class

### PR DESCRIPTION
**Pull request by garyee**
php 7 compatibility

### CODE REVIEW

**Comment by bytehead** [comment]
That change would make it incompatible with `contao < 3.5.1`.

You've could compare it like this:

``` php
if (version_compare(VERSION.'.'.BUILD, '3.5.1', '>=')) {
    // use StringUtil
} else {
    // use String
}
```

**Comment by bytehead** [comment]
See also https://github.com/contao/core/commit/007b2af22011307e2f2ccbf39a15823c717aeb28

**Comment by garyee** [comment]
That is kind of your choice, either break compatibility, or blow up the code... (at 61 Points)
(or create a new branch, which would be more of a temporary solution)

**Comment by bytehead** [comment]
I don't really care that much. We don't use EFG anymore. I can merge it an release a new major version to be sure existing installations don't get broken on update.

**Comment by bytehead** [comment]
I've actually found other bricks on PHP7: https://github.com/1up-lab/contao-efg/blob/master/classes/Formdata.php#L2204

All hook calls must be updated as well because of the indirect access.

**Comment by garyee** [comment]
... those curly brackets ...

**Comment by bytehead** [comment]
Exactly.

**Review by bytehead — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Comment by bytehead** [comment]
You can use version [3.0.0](https://github.com/1up-lab/contao-efg/releases/tag/3.0.0) for PHP 7 now.

**Comment by garyee** [comment]
Tanks, please do not forget to update the composer Json.

**Comment by bytehead** [comment]
Just noticed that. Thank you.

**Pull request merged**
